<?php $link = new \App\DB\Database();
$book_id = $_GET['book_id'];
//$book_id = $_REQUEST;
$allBooks = $link->takeSelectBook('books', '*', $book_id);
//$allBooks = $link->takeSelectBook();

//$all = $_POST;
//$id = $_POST['id'];
//$name = $_POST['name'];
//$content = $_POST['content'];
//$dateWrite = $_POST['date_write_book'];
//$genre = $_POST['genre'];
//$author = $_POST['author'];
//$countPages = $_POST['count_of_pages'];


?>
<?php require_once('header.phtml'); ?>
<form action="../update" method="post" name="EditBook">
    <div class="listBooks">
        <?php foreach ($allBooks as $oneBook) : ?>
            <div style="display:grid; border: 1px solid black; margin: 10px; padding: 10px" class="oneBook"
                 id="<?= $oneBook['id'] ?>">
                <input type="hidden" name="id" value="<?=$oneBook['id'] ?>">
                <input type="text" name="name" value="<?=$oneBook['name']; ?>">
                <input type="text" name="content" value="<?=$oneBook['content']; ?>">
                <input type="text" name="date_write_book" value="<?=$oneBook['date_write_book']; ?>">
                <input type="text" name="genre" value="<?=$oneBook['genre']; ?>">
                <input type="text" name="author" value="<?=$oneBook['author']; ?>">
                <input type="text" name="count_of_pages" value="<?=$oneBook['count_of_pages']; ?>">
                <input type="submit" value="Update" style="background: green">
            </div>
        <?php endforeach; ?>
    </div>
</form>
<?php require_once('footer.phtml'); ?>
