<?php $link = new \App\DB\Database();
//$book_id = $_POST['book_id'];
$allBooks = $link->takeSelectBook('books', '*', 2);
//$allBooks = $link->takeSelectBook();
?>
<?php require_once('header.phtml'); ?>
<form action="save" method="post">
    <div class="listBooks">
        <?php foreach ($allBooks as $oneBook) : ?>
            <div style="display:grid; border: 1px solid black; margin: 10px; padding: 10px" class="oneBook"
                 id="<?= $oneBook['id'] ?>">
                <input type="hidden" name="id" value="<?= $oneBook['id'] ?>">
                <input type="text" name="name" value="<?= $oneBook['name']; ?>">
                <textarea><?= $oneBook['content']; ?></textarea>
                <input type="text" name="date_write_book" value="<?= $oneBook['date_write_book']; ?>">
                <input type="text" name="genre" value="<?= $oneBook['genre']; ?>">
                <input type="text" name="author" value="<?= $oneBook['author']; ?>">
                <input type="text" name="count_of_pages" value="<?= $oneBook['count_of_pages']; ?>">
                <div>
                    <a href="#">
                        <button>Save</button>
                    </a>

                </div>
            </div>
        <?php endforeach; ?>
    </div>
</form>
<?php require_once('footer.phtml'); ?>
