<?php $link = new \App\DB\Database();
$allBooks = $link->selectBooks('books', '*');
?>
<?php require_once('header.phtml'); ?>
<div class="crud">
    <h1>CRUD APP</h1>
    <div class="crudForm">
        <div class="listBooks">
            <?php foreach ($allBooks as $oneBook) : ?>
                <div style="display: flex; border: 1px solid black; margin: 10px; padding: 10px" class="oneBook"
                     id="<?= $oneBook['id'] ?>">
                    <p><?= $oneBook['name']; ?></p>
                    <p><?= substr($oneBook['content'], 1, 100); ?></p>
                    <p><?= $oneBook['date_write_book']; ?></p>
                    <p><?= $oneBook['genre']; ?></p>
                    <p><?= $oneBook['author']; ?></p>
                    <p><?= $oneBook['count_of_pages']; ?></p>
                    <div>
                        <a href="/edit/<?= $oneBook['id'] ?>"><button>Edit</button></a>
<!--                        <a href="edit"><button>Edit</button></a>-->
                        <button>Delete</button>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <p>If you want to add new book fill the fields and press send</p>
        <input type="text" name="name" placeholder="enter name book">
        <input type="text" name="content" placeholder="enter content book">
        <p>enter date write book<input type="datetime-local" name="date_write_book"
                                       placeholder="enter date write book "></p>
        <input type="text" name="genre" placeholder="enter genre">
        <input type="text" name="author" placeholder="enter author">
        <input type="number" name="count_of_pages" placeholder="enter count of pages">
        <button>Send</button>

    </div>
</div>
<?php require_once('footer.phtml'); ?>
